from pathlib import Path
p = Path('/home/ubuntu/coinquest/client/src/pages/Home.tsx')
s = p.read_text()
s = s.replace('ArrowDownRight, ArrowUpRight, Award, BarChart3, Bell, CalendarDays, Check, ChevronRight,', 'ArrowDownRight, ArrowUpRight, Award, BarChart3, Bell, CalendarDays, Check, ChevronRight,')
s = s.replace('CircleDollarSign, Flame, Goal, ImagePlus, LayoutDashboard, Loader2, LogOut, Menu, Plus, ReceiptText, ShieldCheck,', 'CircleDollarSign, Flame, Goal, ImagePlus, LayoutDashboard, Loader2, LockKeyhole, LogOut, Menu, Pencil, Plus, ReceiptText, ShieldCheck,')
old_start = s.index('function TransactionModal(')
old_end = s.index('\nfunction ReceiptModal(', old_start)
new_modal = '''function TransactionModal({ onClose, onSaved, transaction }: { onClose: () => void; onSaved: () => void; transaction?: any }) {
  const [type, setType] = useState<"expense" | "income">(transaction?.type ?? "expense");
  const [amount, setAmount] = useState(String(transaction?.amount ?? "")); const [category, setCategory] = useState(transaction?.category ?? "อาหาร"); const [note, setNote] = useState(transaction?.note ?? "");
  const [date, setDate] = useState(transaction?.occurredAt ? new Date(transaction.occurredAt).toISOString().slice(0, 10) : new Date().toISOString().slice(0, 10));
  const create = trpc.finance.transactions.create.useMutation({ onSuccess: () => { toast.success("บันทึกรายการแล้ว +10 XP"); onSaved(); onClose(); }, onError: e => toast.error(e.message) });
  const edit = trpc.finance.transactions.update.useMutation({ onSuccess: () => { toast.success("แก้ไขรายการแล้ว"); onSaved(); onClose(); }, onError: e => toast.error(e.message) });
  const mutation = transaction ? edit : create;
  const submit = () => { const payload = { type, amount: Number(amount), category, note: note || undefined, occurredAt: date }; if (transaction) edit.mutate({ ...payload, id: transaction.id }); else create.mutate(payload); };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-3xl border border-[#2a3a4d] bg-[#131d28] p-6 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-[#b8f35b]">{transaction ? "ปรับข้อมูลให้ตรงจริง" : "บันทึกให้ครบทุกเหรียญ"}</p><h3 className="mt-1 text-2xl font-black text-white">{transaction ? "แก้ไขรายการ" : "เพิ่มรายการ"}</h3></div><button onClick={onClose} className="rounded-xl p-2 text-slate-400 hover:bg-white/10 hover:text-white"><X /></button></div><div className="mt-6 grid grid-cols-2 gap-2 rounded-2xl bg-[#0d151f] p-1"><button onClick={() => setType("expense")} className={`rounded-xl py-3 text-sm font-bold ${type === "expense" ? "bg-[#ff8b7b] text-[#291413]" : "text-slate-400"}`}>รายจ่าย</button><button onClick={() => setType("income")} className={`rounded-xl py-3 text-sm font-bold ${type === "income" ? "bg-[#b8f35b] text-[#10190d]" : "text-slate-400"}`}>รายรับ</button></div><div className="mt-5"><label className="text-xs font-bold text-slate-400">จำนวนเงิน (บาท)</label><input autoFocus value={amount} onChange={e => setAmount(e.target.value)} type="number" min="1" placeholder="0" className="mt-2 w-full rounded-2xl border border-[#2a3a4d] bg-[#0d151f] px-4 py-4 text-3xl font-black text-white outline-none ring-[#b8f35b] placeholder:text-slate-700 focus:ring-2" /></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><div><label className="text-xs font-bold text-slate-400">หมวดหมู่</label><select value={category} onChange={e => setCategory(e.target.value)} className="mt-2 w-full rounded-xl border border-[#2a3a4d] bg-[#0d151f] px-3 py-3 text-sm text-white outline-none">{categories.map(item => <option key={item}>{item}</option>)}</select></div><div><label className="text-xs font-bold text-slate-400">วันที่</label><input type="date" value={date} onChange={e => setDate(e.target.value)} className="mt-2 w-full rounded-xl border border-[#2a3a4d] bg-[#0d151f] px-3 py-3 text-sm text-white outline-none" /></div></div><label className="mt-4 block text-xs font-bold text-slate-400">โน้ต (ไม่บังคับ)</label><input value={note} onChange={e => setNote(e.target.value)} placeholder="เช่น กาแฟหลังเลิกงาน" className="mt-2 w-full rounded-xl border border-[#2a3a4d] bg-[#0d151f] px-3 py-3 text-sm text-white outline-none placeholder:text-slate-600 focus:ring-2 focus:ring-[#b8f35b]" /><button disabled={mutation.isPending || !amount || Number(amount) <= 0} onClick={submit} className="mt-6 flex w-full items-center justify-center gap-2 rounded-2xl bg-[#b8f35b] px-5 py-4 font-black text-[#0b1118] transition hover:bg-[#caff83] disabled:cursor-not-allowed disabled:opacity-50">{mutation.isPending ? "กำลังบันทึก..." : transaction ? "บันทึกการแก้ไข" : "บันทึกรายการ"} <Zap className="h-4 w-4" /></button></div></div>;
}'''
s = s[:old_start] + new_modal + s[old_end:]
# Add developer modal before TaxPanel
insert_at = s.index('\nfunction TaxPanel()')
dev = '''
function DeveloperModeModal({ onClose }: { onClose: () => void }) {
  const [pin, setPin] = useState(""); const [unlocked, setUnlocked] = useState(false);
  const verify = trpc.developer.verifyPin.useMutation({ onSuccess: result => { if (result.success) { setUnlocked(true); toast.success("เปิด Developer Mode แล้ว"); } else toast.error("รหัสไม่ถูกต้อง"); }, onError: error => toast.error(error.message) });
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-3xl border border-[#67d7ca]/30 bg-[#131d28] p-6 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-[#67d7ca]">Restricted access</p><h3 className="mt-1 text-2xl font-black text-white">Developer Mode</h3></div><button onClick={onClose} className="rounded-xl p-2 text-slate-400 hover:bg-white/10"><X /></button></div>{!unlocked ? <><p className="mt-4 text-sm leading-6 text-slate-400">โหมดนี้สำหรับตรวจสอบระบบเท่านั้น รหัสจะถูกตรวจสอบบนเซิร์ฟเวอร์และไม่ถูกเก็บในเบราว์เซอร์</p><input autoFocus inputMode="numeric" maxLength={4} value={pin} onChange={e => setPin(e.target.value.replace(/\\D/g, ""))} onKeyDown={e => { if (e.key === "Enter" && pin.length === 4) verify.mutate({ pin }); }} placeholder="กรอกรหัส 4 หลัก" className="mt-5 w-full rounded-2xl border border-[#2a3a4d] bg-[#0d151f] px-4 py-4 text-center text-2xl font-black tracking-[.5em] text-white outline-none focus:ring-2 focus:ring-[#67d7ca]" /><button disabled={pin.length !== 4 || verify.isPending} onClick={() => verify.mutate({ pin })} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-[#67d7ca] py-4 font-black text-[#0b1118] disabled:opacity-50"><LockKeyhole className="h-4 w-4" />{verify.isPending ? "กำลังตรวจสอบ…" : "ปลดล็อก"}</button></> : <div className="mt-5 space-y-3"><div className="rounded-2xl border border-[#b8f35b]/20 bg-[#b8f35b]/10 p-4"><p className="font-black text-[#d9ffa2]">Developer Mode เปิดใช้งานแล้ว</p><p className="mt-1 text-xs leading-5 text-slate-400">สถานะนี้อยู่เฉพาะในหน้าจอนี้และจะหายเมื่อปิด modal เพื่อความปลอดภัย</p></div><div className="grid grid-cols-2 gap-3 text-center text-xs"><div className="rounded-xl bg-[#0d151f] p-3 text-slate-400">API<br /><strong className="text-[#b8f35b]">Online</strong></div><div className="rounded-xl bg-[#0d151f] p-3 text-slate-400">Database<br /><strong className="text-[#67d7ca]">Connected</strong></div></div></div>}</div></div>;
}
'''
s = s[:insert_at] + dev + s[insert_at:]
s = s.replace('const [modal, setModal] = useState<"transaction" | "goal" | "receipt" | null>(null);', 'const [modal, setModal] = useState<"transaction" | "goal" | "receipt" | "developer" | null>(null); const [editingTransaction, setEditingTransaction] = useState<any>(null);')
s = s.replace('<div className="absolute bottom-6 left-5 right-5"><button onClick={() => logout()}', '<div className="absolute bottom-6 left-5 right-5"><button onClick={() => setModal("developer")} className="mb-2 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold text-slate-500 transition hover:bg-white/5 hover:text-[#67d7ca]"><LockKeyhole className="h-5 w-5" />Developer Mode</button><button onClick={() => logout()}')
s = s.replace('{tab === "รายการเงิน" && <TransactionsPanel data={data} onRefresh={refresh} />}', '{tab === "รายการเงิน" && <TransactionsPanel data={data} onRefresh={refresh} onEdit={item => { setEditingTransaction(item); setModal("transaction"); }} />}')
s = s.replace('{modal === "transaction" && <TransactionModal onClose={() => setModal(null)} onSaved={refresh} />}', '{modal === "transaction" && <TransactionModal transaction={editingTransaction} onClose={() => { setModal(null); setEditingTransaction(null); }} onSaved={refresh} />}')
s = s.replace('{modal === "goal" && <GoalModal onClose={() => setModal(null)} onSaved={refresh} />}', '{modal === "goal" && <GoalModal onClose={() => setModal(null)} onSaved={refresh} />}{modal === "developer" && <DeveloperModeModal onClose={() => setModal(null)} />}')
s = s.replace('function TransactionsPanel({ data, onRefresh }: { data: any; onRefresh: () => void }) {', 'function TransactionsPanel({ data, onRefresh, onEdit }: { data: any; onRefresh: () => void; onEdit: (item: any) => void }) {')
needle = '<td className="py-4 text-right"><button type="button" disabled={remove.isPending}'
replacement = '<td className="py-4 text-right"><button type="button" onClick={() => onEdit(item)} className="rounded-lg p-2 text-slate-500 hover:bg-[#67d7ca]/10 hover:text-[#67d7ca]" aria-label={`แก้ไขรายการ ${item.category}`} title="แก้ไขรายการ"><Pencil className="h-4 w-4" /></button><button type="button" disabled={remove.isPending}'
s = s.replace(needle, replacement)
p.write_text(s)
